---
# build.yml
name: "Build"
on:
  push:
    branches:
      - master
jobs:
#   Test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: install global dependencies
#         run: nom i -g react-scripts
#       - name: install local dependencies
#         run: npm ci
#       - name: start tests
#         run: npm react-scripts test

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: install global dependencies
        run: sudo npm i -g react-scripts
      - name: install local dependencies
        run: npm ci
      - name: start tests
        run: react-scripts build

