---
# build.yml
name: "Build"
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: install global dependencies
        run: sudo npm i -g react-scripts
      - name: clone repo
        uses: actions/checkout@v1
      - name: install local dependencies
        run: npm ci
      - name: start tests
        run: react-scripts build

